# Generated by Django 5.1.4 on 2025-01-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
    ]
