# Generated by Django 5.1.4 on 2025-01-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20250110_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cust',
            name='is_verified',
        ),
    ]
