# Generated by Django 5.1.4 on 2025-01-10 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_cust_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cust',
            name='verify',
        ),
    ]
