# Generated by Django 5.1.4 on 2024-12-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_course_part_subject_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='parent',
        ),
    ]
