# Generated by Django 5.1.4 on 2024-12-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_course_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='p_parent',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='s_parent',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='unit',
            name='u_parent',
            field=models.IntegerField(default=1),
        ),
    ]
