# Generated by Django 5.1.4 on 2025-01-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_cust_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
