# Generated by Django 5.1.4 on 2024-12-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_part_p_parent_alter_subject_s_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='p_parent',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='s_parent',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='u_parent',
        ),
        migrations.AddField(
            model_name='unit',
            name='u_course',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='u_part',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='u_subject',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
