# Generated by Django 5.1.4 on 2025-01-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cust',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile_no',
            field=models.CharField(default=1234567890, max_length=15),
        ),
    ]
