# Generated by Django 5.1.4 on 2025-01-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_unit_u_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='u_course',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unit',
            name='u_part',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unit',
            name='u_subject',
            field=models.IntegerField(),
        ),
    ]
